### ISSUE TITLE
Gratitude <3

### ISSUE THREAD

**Issue by selvagsz** [DZNS/RazorNode#4]
@dezinezync We're glad to inform that we've released an official node sdk package [razorpay@0.0.1](https://github.com/razorpay/razorpay-node). The sdk will have all the latest features that we release. 

`razorNode` has served well for few of our customers. We really appreciate your contributions & thanks for your amazing work 💯 

Feel free to close the issue

**Comment by dezinezync** [comment]
Congratulations. Will update Docs here to mention that. Shall follow up on future stuff on that repo as PRs. 

Cheers.
